services:
  postgres:
    image: postgres:16-alpine
    container_name: quizzer-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: quizzer
      POSTGRES_PASSWORD: quizzer123
      POSTGRES_DB: quizzer
    ports:
      - "5432:5432"
    volumes:
      - quizzer_pg_data:/var/lib/postgresql/data

volumes:
  quizzer_pg_data:
